# Generated by Django 5.2.16 on 2026-07-13 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectjoinrequest"),
        ("teams", "0002_remove_team_department_team_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectjoinrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="projectjoinrequest",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="teams.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectjoinrequest",
            unique_together={("project", "user", "team")},
        ),
    ]
