# Generated by Django 5.2.16 on 2026-07-09 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_task_assigned", models.BooleanField(default=True)),
                ("in_app_task_assigned", models.BooleanField(default=True)),
                ("email_task_review", models.BooleanField(default=True)),
                ("in_app_task_review", models.BooleanField(default=True)),
                ("email_task_completed", models.BooleanField(default=True)),
                ("in_app_task_completed", models.BooleanField(default=True)),
                ("email_task_needs_changes", models.BooleanField(default=True)),
                ("in_app_task_needs_changes", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("in_app_messages", models.BooleanField(default=True)),
                ("email_meetings", models.BooleanField(default=True)),
                ("in_app_meetings", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
