# Generated by Django 5.2.16 on 2026-07-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("medium", "Medium"),
                    ("urgent", "Urgent"),
                    ("top", "Top"),
                ],
                default="normal",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task", "Task"),
                    ("meeting", "Meeting"),
                    ("announcement", "Announcement"),
                    ("reminder", "Reminder"),
                    ("system", "System"),
                    ("message", "Message"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
