# Generated by Django 5.2.15 on 2026-07-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_team"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="department",
        ),
        migrations.AddField(
            model_name="team",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="projects.project",
            ),
        ),
    ]
