# Generated by Django 5.2.16 on 2026-07-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_knowledgearticle_file_upload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgearticle",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
