# Generated by Django 5.2.15 on 2026-07-04 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('participation', 'Participation'), ('workshop', 'Workshop'), ('achievement', 'Achievement'), ('completion', 'Completion'), ('volunteer', 'Volunteer'), ('custom', 'Custom')], max_length=20)),
                ('html_template', models.TextField(help_text='HTML template with {{name}}, {{event}}, {{date}} placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('event_name', models.CharField(blank=True, max_length=300)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.CharField(max_length=20, unique=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
