# Generated by Django 5.2.15 on 2026-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="year",
        ),
        migrations.AddField(
            model_name="user",
            name="batch",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="enrollment_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
