# Generated by Django 5.2.16 on 2026-07-09 10:21

import apps.accounts.models
from django.db import migrations, models


def truncate_enrollment_numbers(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        if user.enrollment_number and len(user.enrollment_number) > 12:
            user.enrollment_number = user.enrollment_number[:12]
            user.save(update_fields=["enrollment_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_year_user_batch_user_enrollment_number"),
    ]

    operations = [
        migrations.RunPython(truncate_enrollment_numbers),
        migrations.AlterField(
            model_name="user",
            name="enrollment_number",
            field=models.CharField(
                blank=True,
                help_text="12-character code: 4 college + 2 alpha branch + 2 year + 4 number. E.g. 0612IA240001",
                max_length=12,
                validators=[apps.accounts.models.validate_enrollment_number],
            ),
        ),
    ]
