# Generated by Django 5.2.16 on 2026-07-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_enrollment_number_12digit_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="slug",
            field=models.CharField(
                choices=[
                    ("founder", "Founder"),
                    ("super_admin", "Super Admin"),
                    ("president", "President"),
                    ("vice_president", "Vice President"),
                    ("faculty", "Faculty"),
                    ("mentor", "Mentor"),
                    ("team_lead", "Team Lead"),
                    ("member", "Member"),
                    ("guest", "Guest"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
