"""PDF report generation using ReportLab."""

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from .models import Report


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "ReportTitle",
            parent=base["Heading1"],
            fontSize=20,
            textColor=colors.HexColor("#6366f1"),
            spaceAfter=12,
        ),
        "subtitle": ParagraphStyle(
            "ReportSubtitle",
            parent=base["Normal"],
            fontSize=10,
            textColor=colors.grey,
            spaceAfter=20,
        ),
        "heading": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontSize=13,
            textColor=colors.HexColor("#1e293b"),
            spaceBefore=16,
            spaceAfter=8,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontSize=10,
            leading=14,
        ),
    }


def _escape(text) -> str:
    s = str(text or "")
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def generate_report_pdf(report: Report) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    styles = _styles()
    story = []

    story.append(Paragraph("HumorphicOS", styles["subtitle"]))
    story.append(Paragraph(_escape(report.title), styles["title"]))

    meta = [
        f"<b>Type:</b> {report.get_report_type_display()}",
        f"<b>Period:</b> {report.period_start or '—'} to {report.period_end or '—'}",
        f"<b>Generated:</b> {report.created_at.strftime('%d %b %Y, %H:%M')}",
    ]
    if report.generated_by:
        meta.append(f"<b>By:</b> {_escape(report.generated_by.get_full_name())}")
    story.append(Paragraph(" &nbsp;|&nbsp; ".join(meta), styles["subtitle"]))
    story.append(Spacer(1, 0.5 * cm))

    data = report.data or {}

    if report.report_type == Report.ReportType.DAILY:
        story.append(Paragraph("Summary", styles["heading"]))
        summary_rows = [
            ["Metric", "Value"],
            ["Date", data.get("date", "—")],
            ["Daily Updates Submitted", str(data.get("daily_updates_count", 0))],
            ["Tasks Completed", str(data.get("tasks_completed", 0))],
        ]
        story.append(_table(summary_rows))
        updates = data.get("updates") or []
        if updates:
            story.append(Paragraph("Member Updates", styles["heading"]))
            rows = [["Member", "Hours", "Work Done"]]
            for u in updates:
                rows.append([
                    _escape(u.get("user", "")),
                    str(u.get("hours", 0)),
                    _escape(u.get("work_done", ""))[:120],
                ])
            story.append(_table(rows, col_widths=[4 * cm, 2 * cm, 11 * cm]))

    elif report.report_type == Report.ReportType.WEEKLY:
        story.append(Paragraph("Weekly Summary", styles["heading"]))
        rows = [
            ["Metric", "Value"],
            ["Week Start", data.get("week_start", "—")],
            ["Week End", data.get("week_end", "—")],
            ["Daily Updates", str(data.get("daily_updates", 0))],
            ["Tasks Updated", str(data.get("tasks_updated", 0))],
            ["Tasks Completed", str(data.get("tasks_completed", 0))],
        ]
        story.append(_table(rows))

    else:
        story.append(Paragraph("Report Data", styles["heading"]))
        rows = [["Field", "Value"]]
        for key, val in data.items():
            if isinstance(val, (list, dict)):
                val = str(val)[:200]
            rows.append([_escape(key), _escape(val)])
        story.append(_table(rows))

    story.append(Spacer(1, 1 * cm))
    story.append(
        Paragraph(
            "<i>Generated by HumorphicOS — Humorphic Robotics Club</i>",
            styles["subtitle"],
        )
    )

    doc.build(story)
    return buffer.getvalue()


def _table(rows, col_widths=None):
    t = Table(rows, colWidths=col_widths, repeatRows=1)
    t.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#6366f1")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("TOPPADDING", (0, 0), (-1, 0), 8),
            ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ])
    )
    return t
