# Generated by Django 5.2.15 on 2026-07-05 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_friendrequest"),
        ("departments", "0002_department_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.department",
            ),
        ),
    ]
