# Generated by Django 5.2.15 on 2026-07-05 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="departments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
