# Generated by Django 5.2.16 on 2026-07-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
        ("teams", "0002_remove_team_department_team_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.team",
            ),
        ),
    ]
