# Generated by Django 5.2.16 on 2026-07-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_meeting_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="reminder_15m_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="reminder_5m_sent",
            field=models.BooleanField(default=False),
        ),
    ]
